### 1. PyTorch Tensors and Basic Operations (Using Iris Data)

In [ ]:
import torch
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
# loading the dataset officially 
iris = load_iris()

X = iris.data          # shape: (150, 4)
y = iris.target        # shape: (150,)


In [3]:
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.long)
# convert the numpy array into pytorch tensors

In [4]:
# different tensor initializations 
a = torch.zeros((2, 3))
b = torch.ones((2, 3))
c = torch.rand((2, 3))
d = torch.eye(3)


In [5]:
print(a.dtype, c.shape)


torch.float32 torch.Size([2, 3])


In [6]:
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

print(x + y)
print(x * y)
# performing arithmetic tensor operations

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])


In [7]:
A = torch.rand((3, 3))
b = torch.rand((3,))

print(A + b)
# broadcasting

tensor([[1.0008, 0.6093, 1.3894],
        [1.1803, 0.9396, 1.3989],
        [0.8527, 0.7373, 1.3495]])


In [8]:
print(X_tensor[:5])       # first 5 samples
print(X_tensor[:, 0])     # first feature
# indexing and slicing 

tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000]])
tensor([5.1000, 4.9000, 4.7000, 4.6000, 5.0000, 5.4000, 4.6000, 5.0000, 4.4000,
        4.9000, 5.4000, 4.8000, 4.8000, 4.3000, 5.8000, 5.7000, 5.4000, 5.1000,
        5.7000, 5.1000, 5.4000, 5.1000, 4.6000, 5.1000, 4.8000, 5.0000, 5.0000,
        5.2000, 5.2000, 4.7000, 4.8000, 5.4000, 5.2000, 5.5000, 4.9000, 5.0000,
        5.5000, 4.9000, 4.4000, 5.1000, 5.0000, 4.5000, 4.4000, 5.0000, 5.1000,
        4.8000, 5.1000, 4.6000, 5.3000, 5.0000, 7.0000, 6.4000, 6.9000, 5.5000,
        6.5000, 5.7000, 6.3000, 4.9000, 6.6000, 5.2000, 5.0000, 5.9000, 6.0000,
        6.1000, 5.6000, 6.7000, 5.6000, 5.8000, 6.2000, 5.6000, 5.9000, 6.1000,
        6.3000, 6.1000, 6.4000, 6.6000, 6.8000, 6.7000, 6.0000, 5.7000, 5.5000,
        5.5000, 5.8000, 6.0000, 5.4000, 6.0000, 6.7000, 6.3000, 5.600

In [10]:
reshaped = X_tensor.view(-1, 2)
print(reshaped.shape)
# reshaping


torch.Size([300, 2])


In [11]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2 + 3*x + 1

y.backward()
print(x.grad)
# automatic differentiation (autograd)

tensor(7.)


### 2. Linear Algebra Operations Using TensorFlow

In [12]:
import tensorflow as tf


In [13]:
A = tf.constant([[1., 2.], [3., 4.]])
B = tf.constant([[5., 6.], [7., 8.]])
# performing the matrix operations

In [14]:
tf.add(A, B)
# addition

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float32)>

In [15]:
tf.matmul(A, B)
# multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [16]:
tf.transpose(A)
# transpose

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [2., 4.]], dtype=float32)>

In [17]:
tf.linalg.det(A)
# determinant

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [18]:
tf.linalg.inv(A)
# inverse

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [19]:
tf.linalg.eig(A)
# eigen values

(<tf.Tensor: shape=(2,), dtype=complex64, numpy=array([-0.37228122+0.j,  5.372281  +0.j], dtype=complex64)>,
 <tf.Tensor: shape=(2, 2), dtype=complex64, numpy=
 array([[-0.8245648 +0.j, -0.41597357+0.j],
        [ 0.56576747+0.j, -0.90937674+0.j]], dtype=complex64)>)

### 3. AND / OR Gates Using Perceptron

In [20]:
# y=step(w1​x1​+w2​x2​+b) perceptron logic
import numpy as np

def perceptron(x, w, b):
    return 1 if np.dot(w, x) + b >= 0 else 0


In [21]:
w_and = np.array([1, 1])
b_and = -1.5

for x in [(0,0),(0,1),(1,0),(1,1)]:
    print(x, perceptron(x, w_and, b_and))
# and gate

(0, 0) 0
(0, 1) 0
(1, 0) 0
(1, 1) 1


In [22]:
w_or = np.array([1, 1])
b_or = -0.5

for x in [(0,0),(0,1),(1,0),(1,1)]:
    print(x, perceptron(x, w_or, b_or))
# or gate

(0, 0) 0
(0, 1) 1
(1, 0) 1
(1, 1) 1


### 4. XOR Problem Using PyTorch Neural Network

In [24]:
# XOR need NN because it is not linearly separable 

X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])
# dataset


In [25]:
import torch.nn as nn

class XORNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(2, 2)
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.relu(self.hidden(x))
        return torch.sigmoid(self.output(x))
# defining the NN

In [26]:
model = XORNet()
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = model(X)
    loss = criterion(y_pred, y)
    loss.backward()
    optimizer.step()
# training

In [27]:
print(model(X).round())
# results

tensor([[0.],
        [0.],
        [1.],
        [0.]], grad_fn=<RoundBackward0>)


### 5. Simple Neural Network for Regression according to the Diagram

Architecture :

2 Inputs: x1, x2
Hidden Layer: 2 neurons
Output Layer: 1 neuron
Activation: ReLU (hidden), Linear (output)

In [28]:
X = torch.rand((100, 2))
y = 3*X[:,0] + 2*X[:,1] + 1
y = y.view(-1,1)
# synthetic regression data

In [29]:
class SimpleRegNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.h1 = nn.Linear(2, 2)   # input → hidden
        self.out = nn.Linear(2, 1) # hidden → output

    def forward(self, x):
        z1 = torch.relu(self.h1(x))
        return self.out(z1)


In [30]:
model = SimpleRegNet()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.05)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = model(X)
    loss = criterion(y_pred, y)
    loss.backward()
    optimizer.step()

    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")


Epoch 0, Loss: 15.5847
Epoch 100, Loss: 1.0723
Epoch 200, Loss: 1.0723
Epoch 300, Loss: 1.0723
Epoch 400, Loss: 1.0723
Epoch 500, Loss: 1.0723
Epoch 600, Loss: 1.0723
Epoch 700, Loss: 1.0723
Epoch 800, Loss: 1.0723
Epoch 900, Loss: 1.0723


In [ ]:
test = torch.tensor([[0.5, 0.8]])
print(model(test))  
# prediction

tensor([[3.4350]], grad_fn=<AddmmBackward0>)
